### ISSUE TITLE
graceful unzip

### ISSUE THREAD

**Issue by odinuv** [keboola/processor-unziper#1]
- support both unzip and ungzip
- unzip only files which are archives, leave others alone

**Comment by ondrejhlavacek** [comment]
unzipovat by to mohlo do folderu, jako sliced file? jinak tam bude děsnej chaos, v zipu může bejt víc souborů a může se to dost potlouct.

**Comment by ondrejhlavacek** [comment]
btw nemělo by se to spíš jmenovat `processor-unzip` nebo `processor-decompress`? v `unziper` je navíc typo :-)

**Comment by odinuv** [comment]
no do folderu by to asi unzipovat mohlo - to je super napad, jestli je to sliced nebo ne je tomu fuk, ne?
pokud to bude podporovat (vyhledove) unzip i ungzip (coz bych byl pro), tak +10 za `processor-decompress` :)

**Comment by ondrejhlavacek** [comment]
ungzip/gunzip budem potřebovat pro S3, takže tam netřeba čekat.

**Comment by ondrejhlavacek** [comment]
převaluju v hlavě ještě pár věcí
a) zplacatění struktury (v zipu můžou bejt subfoldery, tak poskládat jména)
b) destination do jedný sliced tabulky volitelně (v zipu víc souborů, víc gzipů, víc zipů)
c) co kolize souborů (víc zipů)? to by se vyřešilo nějakým namespacováním ve jménu
d) `default bucket` (víc souborů v zipu, každej do vlastní tabulky)

nebo to zbytečně moc komplikuju?

**Comment by ondrejhlavacek** [comment]
fixed by https://github.com/keboola/processor-decompress
